name = "invite-message"
main = "src/worker.js"
compatibility_date = "2026-09-20"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "love-invite-media"
